[package]
name = "rust_notifier"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
geolocation = "0.2.1"
notify-rust = "4.11.7"
